# Gauss-Legendre element (https://defelement.org/elements/gauss-legendre.html,
# DefElement: elements/gauss-legendre.def).
#
# Cells/degrees implemented: RefLine, RefQuadrilateral and RefHexahedron, any
# degree (the basis is generated by recurrence). Identity mapping.
#
# Following the reference implementation (symfem "Lagrange variant=legendre"),
# the element is MODAL: the DOF functionals are integral moments against the
# orthonormal (tensor-product) Legendre polynomials and the basis functions
# are those same polynomials -- on Ferrite's [-1, 1]^d reference cells simply
# N_(a...) (ξ) = prod_d sqrt(2 a_d + 1) P_(a_d)(ξ_d), with P_n the standard
# Legendre polynomials and the last index running fastest, matching symfem's
# ordering. Note that this orthonormality is with respect to the NORMALIZED
# measure, i.e. int N_i N_j dξ = 2^dim δ_ij on the reference cell.
#
# All DOFs are moments over the cell, so nothing is associated with the
# boundary: all DOFs are cell DOFs (DiscontinuousLagrange pattern) and the
# element is discontinuous (L2 conformity). This deviates from the DefElement
# metadata, which declares `sobolev: H1` and point-evaluation DOFs at
# vertices and Gauss-Legendre points -- that description does not match
# DefElement's own symfem implementation (whose DOFs are all IntegralAgainst
# functionals on the cell interior); this file follows symfem. Not nodal, so
# `reference_coordinates` is not defined.

"""
    GaussLegendre{shape, order}()

Gauss-Legendre element on tensor-product cells: the modal (orthonormal
tensor-Legendre) basis of Q_order with integral-moment DOFs, following
DefElement's reference implementation. Discontinuous (L2), all DOFs on the
cell. Any degree on RefLine, RefQuadrilateral and RefHexahedron.
"""
struct GaussLegendre{shape, order} <: ScalarInterpolation{shape, order} end

Ferrite.conformity(::GaussLegendre) = Ferrite.L2Conformity()
Ferrite.adjust_dofs_during_distribution(::GaussLegendre) = false

Ferrite.getnbasefunctions(::GaussLegendre{Ferrite.RefHypercube{dim}, order}) where {dim, order} = (order + 1)^dim

# All DOFs in the cell interior (not shared between cells), like
# DiscontinuousLagrange.
Ferrite.volumedof_interior_indices(ip::GaussLegendre) = ntuple(i -> i, Ferrite.getnbasefunctions(ip))

# sqrt(2n + 1) * P_n(x) with P_n the Legendre polynomial: L2-orthonormal on
# [-1, 1] with respect to the normalized measure dξ/2.
function _orthonormal_legendre(n::Int, x::T) where {T}
    p_prev, p = one(x), x
    n == 0 && return p_prev
    for m in 1:(n - 1)
        p_prev, p = p, ((2m + 1) * x * p - m * p_prev) / (m + 1)
    end
    return sqrt(T(2n + 1)) * p
end

function Ferrite.reference_shape_value(ip::GaussLegendre{Ferrite.RefHypercube{dim}, order}, ξ::Vec{dim}, i::Int) where {dim, order}
    1 <= i <= Ferrite.getnbasefunctions(ip) || throw_out_of_range(ip, i)
    # Multi-index of i: the last dimension runs fastest (symfem's ordering)
    rest = i - 1
    v = one(eltype(ξ))
    for d in dim:-1:1
        rest, a = divrem(rest, order + 1)
        v *= _orthonormal_legendre(a, ξ[d])
    end
    return v
end
